In [2]:
from matplotlib import pyplot as plt

plt.style.use('ggplot')
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.serif'] = 'Ubuntu'
plt.rcParams['font.monospace'] = 'Ubuntu Mono'
plt.rcParams['font.size'] = 14
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['axes.labelweight'] = 'bold'
plt.rcParams['axes.titlesize'] = 12
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
plt.rcParams['legend.fontsize'] = 12
plt.rcParams['figure.titlesize'] = 12
plt.rcParams['image.cmap'] = 'jet'
plt.rcParams['image.interpolation'] = 'none'
plt.rcParams['figure.figsize'] = (12, 10)
plt.rcParams['axes.grid']=True
plt.rcParams['lines.linewidth'] = 2
plt.rcParams['lines.markersize'] = 8
colors = ['xkcd:pale orange', 'xkcd:sea blue', 'xkcd:pale red', 'xkcd:sage green', 'xkcd:terra cotta', 'xkcd:dull purple', 'xkcd:teal', 'xkcd: goldenrod', 'xkcd:cadet blue',
'xkcd:scarlet']








# sc =plt.scatter(x = df_numerical['alt error'],y = df_numerical['az error'],s = df_numerical['lag_time'],c=df['colors'])
# # plt.legend(["Venus", "Arcturus", "Vega"])
# # plt.legend([ "Arcturus", "Vega"])
# cmap = {'venus':'goldenrod','Arcturus':'saddlebrown','Vega':'deepskyblue'}

# lp = lambda i,camp: plt.plot([],color=camp, mec="none",
#                         label=f"{i}", ls="", marker="o")[0]
# handles = [lp(name,cmap[name]) for name in np.unique(df['Name'])]
# plt.legend(handles=handles)

In [3]:
import numpy as np

In [4]:
start = np.array([2307.674,1762.081,-3763.111])
end = np.array([3211, 1075,-726])
t_s = 15*60+28


In [5]:
mag=end-start

In [6]:
np.linalg.norm(mag)

3242.240180671074

In [7]:
import math

def cartesian_to_spherical(x, y, z):
    r = math.sqrt(x**2 + y**2 + z**2)
    theta = math.atan2(y, x)
    phi = math.acos(z / r)
    return r, math.degrees(theta), math.degrees(phi)

def spherical_to_cartesian(r, theta, phi):
    theta = math.radians(theta)
    phi= math.radians(phi)

    x = r * math.sin(phi) * math.cos(math.radians(theta))
    y = r * math.sin(phi) * math.sin(theta)
    z = r * math.cos(phi)
    return x, y, z

In [8]:
print("Start: ",cartesian_to_spherical(*start))
print("End: ",cartesian_to_spherical(*end))


Start:  (4753.029890412851, 37.36443010087578, 142.3473721781035)
End:  (3463.123156920643, 18.509859212922787, 102.10110153570189)


In [9]:
def get_angle_crossed(vect1,vect2):
    oo = np.array(cartesian_to_spherical(*vect1)[1:])
    pp = np.array(cartesian_to_spherical(*vect2)[1:])
    return pp-oo


In [10]:
get_angle_crossed(start,end)

array([-18.85457089, -40.24627064])

In [11]:
# Given data
distances_miles = [2014.72, 1909.70, 395.24, 212.93, 48.70, 13.20, 9.21, 6.53, 2.69, 2.32, 1.4, 0.079411, 0.079237]
altitudes_miles = [847.26, 781.63, 81.40, 35.22, 10.04, 8.54, 7.42, 6.05, 2.66, 2.29, 1.36, 0.013725, 0.012468]
velocities_mph = [10585.42, 10678.59, 11931.65, 11988.77, 2465.25, 1068.26, 945.35, 363.01, 200.56, 194.76, 182.36, 3.71, 1.68]
times_str = ["15:28", "14:53", "06:49", "05:54", "04:29", "03:03", "02:46", "02:25", "01:25", "01:18", "01:00", "00:18", "00:16"]

mile_to_km = lambda lis: np.array(lis)*1.60934

distances_km = mile_to_km(distances_miles) # Distance to the landing spot
altitudes_km =mile_to_km(altitudes_miles)  # Altitude above Martian surface
velocities_kph = mile_to_km(velocities_mph)  # Velocities in mph
times_str = ["15:28", "14:53", "06:49", "05:54", "04:29", "03:03", "02:46", "02:25", "01:25", "01:18", "01:00", "00:18", "00:16"]  # Time to touch down "min:sec"

In [12]:
altitudes_km

array([1.36352941e+03, 1.25790842e+03, 1.31000276e+02, 5.66809548e+01,
       1.61577736e+01, 1.37437636e+01, 1.19413028e+01, 9.73650700e+00,
       4.28084440e+00, 3.68538860e+00, 2.18870240e+00, 2.20881915e-02,
       2.00652511e-02])

In [13]:
import math

# # Given data
# distances_miles = [2014.72, 1909.70, 395.24, 212.93, 48.70, 13.20, 9.21, 6.53, 2.69, 2.32, 1.4, 0.079411, 0.079237]
# altitudes_miles = [847.26, 781.63, 81.40, 35.22, 10.04, 8.54, 7.42, 6.05, 2.66, 2.29, 1.36, 0.013725, 0.012468]
# velocities_kph = [10585.42, 10678.59, 11931.65, 11988.77, 2465.25, 1068.26, 945.35, 363.01, 200.56, 194.76, 182.36, 3.71, 1.68]
# times_str = ["15:28", "14:53", "06:49", "05:54", "04:29", "03:03", "02:46", "02:25", "01:25", "01:18", "01:00", "00:18", "00:16"]

# Convert time strings to seconds
def time_to_seconds(time_str):
    minutes, seconds = map(int, time_str.split(":"))
    return minutes * 60 + seconds

times_seconds = [time_to_seconds(time) for time in times_str]

# Calculate radial distances
radii_km = altitudes_km +3389.5 


# Calculate radial velocities
def compute_radial_tangential_velocities(radii, velocities, times):
    radial_velocities = []
    tangential_velocities = []
    
    for i in range(len(radii) - 1):
        dr = radii[i] - radii[i+1]
        dt = times[i] - times[i+1]
        vr = dr / dt * 3600  # converting from miles per second to miles per hour
        # print(radii,'\n\n',radii[i])
        # print(vr**2)
        vt = math.sqrt(velocities[i]**2 - vr**2)
        
        radial_velocities.append(vr)
        tangential_velocities.append(vt)
    
    # Append 0 for the final point as there's no next point to compare
    radial_velocities.append(0)
    tangential_velocities.append(0)
    
    return radial_velocities, tangential_velocities




    




radial_velocities, tangential_velocities = compute_radial_tangential_velocities(radii_km, velocities_kph, times_seconds)

# Print the results
for i in range(len(tangential_velocities)):
    print(f"Time: {times_str[i]}, Radial Velocity: {radial_velocities[i]:.2f} kph, Tangential Velocity: {tangential_velocities[i]:.2f} kph")


Time: 15:28, Radial Velocity: 10863.87 kph, Tangential Velocity: 13121.96 kph
Time: 14:53, Radial Velocity: 8381.96 kph, Tangential Velocity: 15002.78 kph
Time: 06:49, Radial Velocity: 4864.54 kph, Tangential Velocity: 18575.69 kph
Time: 05:54, Radial Velocity: 1716.28 kph, Tangential Velocity: 19217.52 kph
Time: 04:29, Radial Velocity: 101.05 kph, Tangential Velocity: 3966.14 kph
Time: 03:03, Radial Velocity: 381.70 kph, Tangential Velocity: 1676.29 kph
Time: 02:46, Radial Velocity: 377.96 kph, Tangential Velocity: 1473.69 kph
Time: 02:25, Radial Velocity: 327.34 kph, Tangential Velocity: 483.89 kph
Time: 01:25, Radial Velocity: 306.23 kph, Tangential Velocity: 101.98 kph
Time: 01:18, Radial Velocity: 299.34 kph, Tangential Velocity: 92.94 kph
Time: 01:00, Radial Velocity: 185.71 kph, Tangential Velocity: 227.25 kph
Time: 00:18, Radial Velocity: 3.64 kph, Tangential Velocity: 4.73 kph
Time: 00:16, Radial Velocity: 0.00 kph, Tangential Velocity: 0.00 kph


In [14]:
def compute_distanc(radial_velocities, tangential_velocities, times):

    dist_tangent = []

    for i in range(len(tangential_velocities) - 1):
        dt = times[i] - times[i+1]
        vr = radial_velocities  # converting from miles per second to miles per hour
        # print(radii,'\n\n',radii[i])
        # print(vr**2)
        vt = tangential_velocities[i]


        dist_tangent.append(dt*vt)

    return dist_tangent


dist_tangent = compute_distanc(radial_velocities, tangential_velocities, times_seconds)
# Print the results

for i in range(len(dist_tangent)):
    print(f"Time: {times_str[i]}, distance tangent: {dist_tangent[i]:.2f} kph, Tangential Velocity: {tangential_velocities[i]:.2f} kph")

Time: 15:28, distance tangent: 459268.67 kph, Tangential Velocity: 13121.96 kph
Time: 14:53, distance tangent: 7261347.25 kph, Tangential Velocity: 15002.78 kph
Time: 06:49, distance tangent: 1021662.88 kph, Tangential Velocity: 18575.69 kph
Time: 05:54, distance tangent: 1633489.27 kph, Tangential Velocity: 19217.52 kph
Time: 04:29, distance tangent: 341087.90 kph, Tangential Velocity: 3966.14 kph
Time: 03:03, distance tangent: 28496.86 kph, Tangential Velocity: 1676.29 kph
Time: 02:46, distance tangent: 30947.54 kph, Tangential Velocity: 1473.69 kph
Time: 02:25, distance tangent: 29033.18 kph, Tangential Velocity: 483.89 kph
Time: 01:25, distance tangent: 713.88 kph, Tangential Velocity: 101.98 kph
Time: 01:18, distance tangent: 1673.01 kph, Tangential Velocity: 92.94 kph
Time: 01:00, distance tangent: 9544.44 kph, Tangential Velocity: 227.25 kph
Time: 00:18, distance tangent: 9.46 kph, Tangential Velocity: 4.73 kph


In [15]:
sum(dist_tangent)

10817274.33620846

In [16]:
def get_change_in_angle(start,end,dist_tangent):
    total_angle_change = get_angle_crossed(start,end)
    total_distance = sum(dist_tangent)\
    
    angles_in_km =  total_angle_change/total_distance

    angles = []
    for i in range(len(dist_tangent)):
        dist = dist_tangent[i]
        angle = angles_in_km * dist

        angles.append(angle)



    return angles
    

In [17]:
angles_changes = get_change_in_angle(start,end,dist_tangent)
angles_changes

[array([-0.80050791, -1.70873463]),
 array([-12.65656969, -27.01624621]),
 array([-1.78076424, -3.80115357]),
 array([-2.84718112, -6.07748766]),
 array([-0.59451815, -1.26903648]),
 array([-0.04967018, -0.10602413]),
 array([-0.05394173, -0.11514203]),
 array([-0.05060499, -0.10801955]),
 array([-0.00124429, -0.00265602]),
 array([-0.00291606, -0.00622452]),
 array([-0.01663602, -0.03551063]),
 array([-1.64950110e-05, -3.52096412e-05])]

In [18]:
radii_km

array([4753.0294084 , 4647.4084242 , 3520.500276  , 3446.1809548 ,
       3405.6577736 , 3403.2437636 , 3401.4413028 , 3399.236507  ,
       3393.7808444 , 3393.1853886 , 3391.6887024 , 3389.52208819,
       3389.52006525])

In [19]:
# Calculate radial distances
radii_km = altitudes_km +3389.5 


def get_shpere_postions(start,angles_changes,radii_km):
    start_sph = cartesian_to_spherical(*start)
    cords = [start_sph]
    for i in range(1,len(dist_tangent)):
        cords.append([radii_km[i],cords[i-1][1]+angles_changes[i][0],cords[i-1][2]+angles_changes[i][1]])

    return cords

sph_cords = get_shpere_postions(start,angles_changes,radii_km)
sph_cords

[(4753.029890412851, 37.36443010087578, 142.3473721781035),
 [4647.4084242, 24.70786040806419, 115.33112596977541],
 [3520.500276, 22.927096172469607, 111.52997240324999],
 [3446.1809548, 20.07991505149018, 105.45248474024038],
 [3405.6577736, 19.485396903708562, 104.18344825992853],
 [3403.2437636, 19.435726722495478, 104.07742412563034],
 [3401.4413028, 19.381784990527994, 103.96228209685735],
 [3399.236507, 19.331179997444714, 103.8542625476674],
 [3393.7808444, 19.329935703032046, 103.85160652277091],
 [3393.1853886, 19.327019640506474, 103.84538200340572],
 [3391.6887024, 19.31038362283453, 103.80987137451812],
 [3389.5220881915, 19.310367127823536, 103.80983616487688]]

In [20]:
cart_cords = []
for ind,cord in enumerate(sph_cords):
    cords_xyz = spherical_to_cartesian(*cord)
    cart_cords.append(cords_xyz)

    print(f"The coordinates of the spacecraft at time -"+str(times_seconds[ind]),'Seconds', "\n Spherical: ",*np.round(cord,2),"\t Cartesian ",*np.round(cords_xyz,2),'\n\n')

The coordinates of the spacecraft at time -928 Seconds 
 Spherical:  4753.03 37.36 142.35 	 Cartesian  2903.31 1762.08 -3763.11 


The coordinates of the spacecraft at time -893 Seconds 
 Spherical:  4647.41 24.71 115.33 	 Cartesian  4200.44 1755.8 -1988.39 


The coordinates of the spacecraft at time -409 Seconds 
 Spherical:  3520.5 22.93 111.53 	 Cartesian  3274.78 1275.75 -1291.98 


The coordinates of the spacecraft at time -354 Seconds 
 Spherical:  3446.18 20.08 105.45 	 Cartesian  3321.55 1140.41 -918.2 


The coordinates of the spacecraft at time -269 Seconds 
 Spherical:  3405.66 19.49 104.18 	 Cartesian  3301.78 1101.38 -834.48 


The coordinates of the spacecraft at time -183 Seconds 
 Spherical:  3403.24 19.44 104.08 	 Cartesian  3300.98 1098.42 -827.78 


The coordinates of the spacecraft at time -166 Seconds 
 Spherical:  3401.44 19.38 103.96 	 Cartesian  3300.89 1095.46 -820.71 


The coordinates of the spacecraft at time -145 Seconds 
 Spherical:  3399.24 19.33 103.85 

In [21]:
cart_cords

[(2903.307884518872, 1762.0809999999994, -3763.1110000000003),
 (4200.442309033176, 1755.7997860399478, -1988.3887854201546),
 (3274.780028404988, 1275.7529513092213, -1291.980981817112),
 (3321.545379546849, 1140.4090877864437, -918.1975165205231),
 (3301.7821322419863, 1101.38362599762, -834.4791970518446),
 (3300.9794550691554, 1098.4175657376793, -827.7806481286702),
 (3300.88741811006, 1095.4557283314768, -820.7102884021442),
 (3300.288489994309, 1092.5066888179365, -813.957627499491),
 (3295.029310432226, 1090.6981954421854, -812.4985049206214),
 (3294.5394303574053, 1090.3778057487914, -811.9980332376084),
 (3293.588748538154, 1089.1606573619351, -809.5987008195108),
 (3291.4852979686293, 1088.464170539794, -809.0795056101255)]

In [22]:
len(times_seconds) 

13

In [23]:
def interpolate_trajectory(coords, times, step):
    interpolated_coords = []
    interpolated_times = []
    
    for i in range(len(coords) - 1):
        start_coords = np.array(coords[i])
        end_coords = np.array(coords[i + 1])
        start_time = times[i]
        end_time = times[i + 1]
        
        num_steps = int((start_time - end_time) / step)
        
        for j in range(num_steps + 1):
            t = j * step
            fraction = t / (start_time - end_time)
            interpolated_coord = start_coords + fraction * (end_coords - start_coords)
            interpolated_time = start_time - t
            
            interpolated_coords.append(interpolated_coord)
            interpolated_times.append(interpolated_time)
    
    return interpolated_coords, interpolated_times

# Example usage:
step_size = 30  # in seconds
interpolated_coords, interpolated_times = interpolate_trajectory(cart_cords, times_seconds, step_size)

# Print the results
for coord, time in zip(interpolated_coords, interpolated_times):
    print(f"Time: {time:.0f} seconds, Coordinates:", *[f"{o} = {p}" for o,p in  zip(['x','y','z'],coord)])

Time: 928 seconds, Coordinates: x = 2903.307884518872 y = 1762.0809999999994 z = -3763.1110000000003
Time: 898 seconds, Coordinates: x = 4015.1373912454183 y = 1756.697102319955 z = -2241.920530360133
Time: 893 seconds, Coordinates: x = 4200.442309033176 y = 1755.7997860399478 z = -1988.3887854201546
Time: 863 seconds, Coordinates: x = 4143.066547837214 y = 1726.044816945068 z = -1945.2230124695527
Time: 833 seconds, Coordinates: x = 4085.6907866412516 y = 1696.2898478501884 z = -1902.057239518951
Time: 803 seconds, Coordinates: x = 4028.3150254452894 y = 1666.5348787553085 z = -1858.8914665683492
Time: 773 seconds, Coordinates: x = 3970.9392642493276 y = 1636.7799096604288 z = -1815.7256936177473
Time: 743 seconds, Coordinates: x = 3913.5635030533654 y = 1607.024940565549 z = -1772.5599206671454
Time: 713 seconds, Coordinates: x = 3856.1877418574036 y = 1577.2699714706694 z = -1729.3941477165438
Time: 683 seconds, Coordinates: x = 3798.8119806614413 y = 1547.5150023757897 z = -1686.22

In [24]:
def interpolate_trajectory(coords, times, step):
    interpolated_coords = []
    interpolated_times = []
    
    for i in range(len(coords) - 1):
        start_coords = np.array(coords[i])
        end_coords = np.array(coords[i + 1])
        start_time = times[i]
        end_time = times[i + 1]
        
        num_steps = int((start_time - end_time) / step)
        
        for j in range(num_steps + 1):
            t = j * step
            fraction = t / (start_time - end_time)
            interpolated_coord = start_coords + fraction * (end_coords - start_coords)
            interpolated_time = start_time - t
            
            interpolated_coords.append(interpolated_coord)
            interpolated_times.append(interpolated_time)
    
    return interpolated_coords, interpolated_times

# Example usage:
step_size = 30  # in seconds
interpolated_coords, interpolated_times = interpolate_trajectory(cart_cords, times_seconds, step_size)
f= open('Output.csv','w')
f.write('Time,x,y,z\n')
# Print the results
for coord, time in zip(interpolated_coords, interpolated_times):
    f.write(f"{round(time)},{round(coord[0])},{round(coord[1])},{round(coord[2])}\n")

In [25]:
def interpolate_trajectory(coords, times, step):
    interpolated_coords = []
    interpolated_times = []
    
    for i in range(len(coords) - 1):
        start_coords = np.array(coords[i])
        end_coords = np.array(coords[i + 1])
        start_time = times[i]
        end_time = times[i + 1]
        
        num_steps = int((start_time - end_time) / step)
        
        for j in range(num_steps + 1):
            t = j * step
            fraction = t / (start_time - end_time)
            interpolated_coord = start_coords + fraction * (end_coords - start_coords)
            interpolated_time = start_time - t
            
            interpolated_coords.append(interpolated_coord)
            interpolated_times.append(interpolated_time)
    
    return interpolated_coords, interpolated_times

# Example usage:
step_size = 1  # in seconds
interpolated_coords, interpolated_times = interpolate_trajectory(cart_cords, times_seconds, step_size)
f= open('Output2.csv','w')
f.write('Time,x,y,z\n')
# Print the results
for coord, time in zip(interpolated_coords, interpolated_times):
    f.write(f"{round(time)},{round(coord[0])},{round(coord[1])},{round(coord[2])}\n")